# work with Pandas

## 1. Many ways to create DataFrame
https://www.geeksforgeeks.org/different-ways-to-create-pandas-dataframe/

In [1]:
import pandas as pd
import numpy as np

a = np.array([[2,3,4],[5,6,7]])
print(a, "\n")

b = pd.DataFrame(a)     # no colume-name, no row-names
print(b, "\n")

c = pd.DataFrame(a, columns=['col1', 'col2', 'col3'], index=['index1', 'index2'])  # with colume-name and row-names
print(c, "\n")

d = pd.DataFrame(a, index=['index1', 'index2']) 
print(d, "\n")

[[2 3 4]
 [5 6 7]] 

   0  1  2
0  2  3  4
1  5  6  7 

        col1  col2  col3
index1     2     3     4
index2     5     6     7 

        0  1  2
index1  2  3  4
index2  5  6  7 



## 2. Extract data from DataFrame
https://stackoverflow.com/questions/11285613/selecting-multiple-columns-in-a-pandas-dataframe
* loc gets rows (or columns) with particular labels from the index.
* iloc gets rows (or columns) at particular positions in the index (so it only takes integers).
Here s.iloc[:6] returns the first 6 rows of the Series as expected. However, s.loc[:6] raises a KeyError since 6 is not in the index.
https://stackoverflow.com/questions/31593201/how-are-iloc-ix-and-loc-different

In [3]:
# 1. access by column-name
df = c[['col1','col3']]      # produce a copy 
print(df)

# 2. access by integer index
df1 = c.iloc[:,[0,2]].copy()        
print(df1)

        col1  col3
index1     2     4
index2     5     7
        col1  col3
index1     2     4
index2     5     7


In [21]:
df1 = c.iloc[:,0:2]          #  not produce copy
print(df1)

df1 = c.iloc[:,0:2].copy()          #  produce copy, To avoid the case where changing df1 also changes df
print(df1)

        col1  col3
index1     2     4
index2     5     7


In [ ]:
# 3.To index a DataFrame with integer rows and named columns (labeled columns):
df.loc[df.index[i], 'NAME']              #      where i is a valid integer index and NAME is the name of the column.

## Extract column
df['col1'] or df.col1

## 3. assign value for DataFrame

In [6]:
# create Zeros Frame
df = pd.DataFrame([[0.0]*4]*3, columns=['LC'+str(i+1) for i in range(3)] +["LCmean"])
df

LC1  LC2  LC3  LCmean
0  0.0  0.0  0.0     0.0
1  0.0  0.0  0.0     0.0
2  0.0  0.0  0.0     0.0

In [65]:
## Extract value
df.iloc[1, :] = np.arange(4)
print(df, "\n")

df.iloc[2, 3] = 100
print(df)

   LC1  LC2  LC3  LCmean
0  0.0  0.0  0.0     0.0
1  0.0  1.0  2.0     3.0
2  0.0  0.0  0.0   100.0 

   LC1  LC2  LC3  LCmean
0  0.0  0.0  0.0     0.0
1  0.0  1.0  2.0     3.0
2  0.0  0.0  0.0   100.0


In [73]:
## mean of each column
a = df.mean(axis=0)
a

LC1        0.000000
LC2        0.333333
LC3        0.666667
LCmean    34.333333
dtype: float64

# Change Column Names and Row Indexes in Pandas?
https://cmdlinetips.com/2018/03/how-to-change-column-names-and-row-indexes-in-pandas/
* df.columns assign new names directly --> set for all columns
* df.rename(...)      --> can change name of 1 column

## Read files
Use pd.read_fwf() to read files with fixed-width. But this looks ugly, so use np.loadtxt, after that convert data into pandas frame
https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html

### the path of the current ipynb file from within IPython? 
https://github.com/ipython/ipython/issues/10123

myInfo01 = !echo %cd% # under windows
myInfo02 = !pwd # under linux/mac

## note on Matplotlib
* if use subplot: plt.sth = ax1.set_sth

## Disable iPython Notebook Autoscrolling
* Individual cells: 
 - Cell->Current Outputs->Toggle Scrolling
 - right-click on output --> disable Crolling
* All cells: Cell->All Outputs->Toggle Scrolling

# 4. Hierarchical indexing
for working with higher dimensional data: 3d, 4d,...
https://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html
* NOTE: iloc, loc, ix : just use to extract index (row), cannot use to extract columns. For extracting column, must use df['col']

In [6]:
import pandas as pd
import numpy as np
arrays = [np.array(['bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux']),
            np.array(['one', 'two', 'one', 'two', 'one', 'two', 'one', 'two'])]
df = pd.DataFrame(np.random.randn(8,2), index=arrays)
df

0         1
bar one  0.083715 -0.161591
    two -1.714780 -1.211817
baz one -1.172680  0.652009
    two -0.814605  0.643798
foo one -0.530733 -0.858860
    two  0.623773  0.473498
qux one -0.158116  0.578128
    two  1.707150 -0.429988

In [27]:
print(df.index)
print(df.index.levels)

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('baz', 'one'),
            ('baz', 'two'),
            ('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           )
[['bar', 'baz', 'foo', 'qux'], ['one', 'two']]


In [9]:
df.values

array([[ 0.08371492, -0.16159087],
       [-1.71477955, -1.21181671],
       [-1.17267952,  0.65200889],
       [-0.81460496,  0.64379787],
       [-0.5307326 , -0.85886016],
       [ 0.62377341,  0.47349806],
       [-0.158116  ,  0.57812815],
       [ 1.70715025, -0.42998762]])

## Basic indexing on axis with MultiIndex
https://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html#basic-indexing-on-axis-with-multiindex
* axis with multiIndex, use form of tuples: df.loc[('bar', 'two')]

In [28]:
df.loc['bar']

0         1
one  0.083715 -0.161591
two -1.714780 -1.211817

In [29]:
df.loc[('bar','one')]

0    0.083715
1   -0.161591
Name: (bar, one), dtype: float64

In [30]:
df.loc['bar'][0]

one    0.083715
two   -1.714780
Name: 0, dtype: float64

## Get the mean across multiple Pandas DataFrames
https://stackoverflow.com/questions/25057835/get-the-mean-across-multiple-pandas-dataframes

In [35]:
B=df.groupby(level=1)
B.mean()

0         1
one -0.444453  0.052422
two -0.049615 -0.131127

# II. Combine multiple DataFrames
https://www.kite.com/blog/python/pandas-merge-join-concat/  <br>
* 