In [ ]:
## Save ipynb's DIR & change working folder
if not 'workbookDIR' in globals(): workbookDIR = os.getcwd()     
os.chdir(workbookDIR)

# work with File Names


## 1. Search strings in file name
re module
https://docs.python.org/3/library/re.html

'a.+b'  match any digit between 'a' and 'b' in input string
'\d+'   match any integer digit in input string

In [1]:
import re

name= 'xxx_K300_dd.txt'
# extract Temperature from file name
subString = re.search('_K.+_', name);

print(subString)
print(subString[0])

<_sre.SRE_Match object; span=(3, 9), match='_K300_'>
_K300_


In [8]:
Temp= float(re.search('\d+', subString[0])[0])
print(Temp)

300.0


In [2]:
name= 'xxx_300K.txt'
# extract Temperature from file name
subString = re.search('_.+K', name);

print(subString)
print(subString==None)
print(subString[0])

<_sre.SRE_Match object; span=(3, 8), match='_300K'>
False
_300K


In [12]:
Temp= float(re.search('\d+', subString[0])[0])
print(Temp)

300.0


In [1]:
import re
a="Grid_5x5_Reduced_25_Data1000configs_20191103_Subset_30.txt"
subString = re.search('Subset_\d+', a) 
print(subString.group(0))
print(type(subString.group(0)))

Subset_30
<class 'str'>


In [2]:
a='Grid_8x8_Reduced_16_Data1000configs_2019-11-01_Subset_6.txt'
print(a.replace('.txt',''))

Grid_8x8_Reduced_16_Data1000configs_2019-11-01_Subset_6


## Python 2 problem
in python 2, cannot access result string with subString[0]. must use subString.group(0)

In [5]:
name= 'xxx_300K.txt'
# extract Temperature from file name
subString = re.search('_.+K', name)
Temp= float(re.search('\d+', subString.group(0)).group(0))
print(Temp)

300.0


## if not found

In [6]:
name= 'xxx_300.txt'
# extract Temperature from file name
subString = re.search('_.+K', name);

print(subString==None)
# print(subString[0])

True


## 2. glob module 
https://docs.python.org/3/library/glob.html

In [2]:
import numpy as np 
a = np.asarray([])
print(a)

[]


In [6]:
if not a: print("empty")

empty


c:\devprogram\python37\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  """Entry point for launching an IPython kernel.


$ x = b \rho $

In [2]:
import numpy as np

In [7]:
a = list(range(5))
print(a)
b = np.arange(5)
print(b)

[0, 1, 2, 3, 4]
[0 1 2 3 4]


In [8]:
c = [2, a]
print(c)

[2, [0, 1, 2, 3, 4]]


In [10]:
np.insert(b, 0, 5, axis=0)

array([5, 0, 1, 2, 3, 4])

In [4]:
for i in range(1,5):
    print(i)

1
2
3
4


In [8]:
a=np.loadtxt('Helmholtz_ASpath_Solid_100K.dat',ndmin=2)

In [9]:
a

array([[ 1.00000000e+02, -3.33698295e+00, -2.94576400e-11],
       [ 1.00000000e+02, -3.34935982e+00, -4.62635700e-11],
       [ 1.00000000e+02, -3.34039947e+00, -2.05046500e-11],
       [ 1.00000000e+02, -3.33515905e+00, -2.63748000e-11],
       [ 1.00000000e+02, -3.33144022e+00, -2.35252600e-11],
       [ 1.00000000e+02, -3.32855619e+00, -3.06199000e-11]])

# New style of string Format
https://pyformat.info/
## repeat format
put numbers in a "tuple" to print

In [ ]:
## Interpolate Energy as a specific Temperature
sol_temp = 100, 900, 880
liq_temp = 1300, 900, 880
yinter1 = np.interp(sol_temp, RSsol['Temperature'], RSsol['Fave'])
yinter2 = np.interp(liq_temp, RSliq['Temperature'][::-1], RSliq['Fave'][::-1])    # note: np.interp only work as xp is increasing, a[::-1] reverse order of array
String = 'meltingPoint '+ 'enSolid_%i '*len(sol_temp) +'enLiquid_%i '*len(liq_temp) +'\n\n' +'%.6f '*(1+len(sol_temp)+len(liq_temp))
print(String  % tuple( np.hstack((sol_temp, liq_temp, meltingPoint, yinter1, yinter2)) ) )

# list of all subdirectories in the current directory
https://stackoverflow.com/questions/973473/getting-a-list-of-all-subdirectories-in-the-current-directory

In [5]:
import os,glob
directory = os.getcwd() 
root = [x[0] for x in os.walk(directory)]
dirs = [x[1] for x in os.walk(directory)]
files= [x[2] for x in os.walk(directory)]

In [28]:
# dirs

In [29]:
# subfolders = [ f.path for f in os.scandir(directory) if f.is_dir() ]
subfolders = [ f.name for f in os.scandir(directory) if f.is_dir() ]
subfolders

['#Machine_Learning',
 '.ipynb_checkpoints',
 'Add_Atom_Periodic',
 'ComputeTI',
 'Compute_on_1DumpFile',
 'Crystals_Models',
 'find_Neighbors_SliceBox',
 'find_Roots_fitting',
 'FreeEnergy_calculation',
 'Generate_EAM_tabular',
 'Histrogram_matplotlib',
 'localDensity_Voronoi_surfaceDetect',
 'LocalStressTensor_KEtensor',
 'Local_Order_Parameter',
 'Ovito_Interpreter',
 'Plumed_PYCV',
 'readWriteData',
 'RotationMatrix_DirectionalCosine',
 'Save_Memory',
 'test_MPI']

# use glob:  
https://stackoverflow.com/questions/14798220/how-can-i-search-sub-folders-using-glob-glob-module <br>
There's a lot of confusion on this topic. Let me see if I can clarify it (Python 3.7):

  1.  glob.glob('*.txt')                  :matches all files ending in '.txt' in current directory
  2.  glob.glob('*/*.txt')                :same as 1
  3.  glob.glob('**/*.txt')               :matches all files ending in '.txt' in the immediate subdirectories only, but not in the current directory
  4.  glob.glob('*.txt',recursive=True)   :same as 1
  5.  glob.glob('*/*.txt',recursive=True) :same as 3
  6.  glob.glob('**/*.txt',recursive=True):matches all files ending in '.txt' in the current directory and in all subdirectories
  7.  glob.glob("*/")    to return only directories.
So it's best to always specify recursive=True.
https://stackoverflow.com/questions/6773584/how-is-pythons-glob-glob-ordered

In [35]:
import os,glob
subDirs = glob.glob( "c*/" )
# subDirs = [elem.replace('\\','') for elem in  glob.glob( "c*/" )]
print(subDirs)
files = [glob.glob(myDir +"**/*.txt", recursive=True) for myDir in subDirs]
print(files)

['ComputeTI\\', 'Compute_on_1DumpFile\\', 'Crystals_Models\\']
[['ComputeTI\\TI for Bulk Liquid\\mySetting.txt', 'ComputeTI\\TI for PLATE\\molecular_Pressure_100K.txt'], [], []]


In [21]:
f = glob.glob(directory + "/**/*.txt" , recursive=True )
f

['D:\\work\\Tool_codes\\Tools_Python\\#JupyNotebooks\\ComputeTI\\TI for Bulk Liquid\\mySetting.txt',
 'D:\\work\\Tool_codes\\Tools_Python\\#JupyNotebooks\\ComputeTI\\TI for Bulk Liquid\\ask_Rodolfo_012020\\mySetting.txt',
 'D:\\work\\Tool_codes\\Tools_Python\\#JupyNotebooks\\ComputeTI\\TI for PLATE\\molecular_Pressure_100K.txt',
 'D:\\work\\Tool_codes\\Tools_Python\\#JupyNotebooks\\LocalStressTensor_KEtensor\\kineticTensor_Sheng11_Plate_Al_z001_20x20x20_850K.txt',
 'D:\\work\\Tool_codes\\Tools_Python\\#JupyNotebooks\\Ovito_Interpreter\\avesro.txt',
 'D:\\work\\Tool_codes\\Tools_Python\\#JupyNotebooks\\Ovito_Interpreter\\test_ClusterAnalysis.txt',
 'D:\\work\\Tool_codes\\Tools_Python\\#JupyNotebooks\\Ovito_Interpreter\\test_cluster_sizes.txt',
 'D:\\work\\Tool_codes\\Tools_Python\\#JupyNotebooks\\readWriteData\\testWrite.txt',
 'D:\\work\\Tool_codes\\Tools_Python\\#JupyNotebooks\\readWriteData\\lammps_Simu\\kEinstein.txt',
 'D:\\work\\Tool_codes\\Tools_Python\\#JupyNotebooks\\readWriteD

In [22]:
dir(f)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']