# I. MD trajectories analysis
## 1. freud
https://freud.readthedocs.io/en/stable/ <br>

## 2. MDtraj
https://mdtraj.org/1.9.4/analysis.html

## 3. MDAnalysis 
https://www.mdanalysis.org/about/

## work with DATA file Lammps
https://docs.mdanalysis.org/stable/documentation_pages/coordinates/LAMMPS.html <br>
https://userguide.mdanalysis.org/1.0.0/formats/reference/data.html

* DATA file: MDAnalysis.Universe('fileName', format='data', atom_style='id resid x y z n1 n2 n3')   # atom_style='id resid x y z' 'atomic'  'full'
* DUMP file: MDAnalysis.Universe('fileName', format='lammpsdump') 

*NOTE: just support reader, work primary on MDA.atoms

In [2]:
import MDAnalysis, os
### Working folder
dataDIR=r"D:\work\myCodes\code_Python\#JupyNotebooks\readWriteData" 
os.chdir(dataDIR)

In [3]:
## load an example DATA file
mdaTraj = MDAnalysis.Universe('Model.dat', format='data', atom_style='id type x y z n1 n2 n3') 
mdaTraj.atoms.positions

array([[-2.851055, -4.032   ,  0.      ],
       [-2.851055, -4.032   ,  2.851055],
       [-2.851055, -4.032   ,  5.702109],
       [-2.851055, -4.032   ,  8.553164],
       [-1.425527, -2.016   ,  1.425527],
       [-1.425527, -2.016   ,  4.276582],
       [-1.425527, -2.016   ,  7.127636],
       [-1.425527, -2.016   ,  9.978691],
       [ 0.      , -4.032   ,  0.      ],
       [ 0.      , -4.032   ,  2.851055],
       [ 0.      , -4.032   ,  5.702109],
       [ 0.      , -4.032   ,  8.553164],
       [ 1.425527, -2.016   ,  1.425527],
       [ 1.425527, -2.016   ,  4.276582],
       [ 1.425527, -2.016   ,  7.127636],
       [ 1.425527, -2.016   ,  9.978691]], dtype=float32)

In [8]:
mdaTraj.atoms.bbox()

array([[-16.257025, -16.257025,   0.      ],
       [  8.12851 ,  -8.128512, 113.799164]], dtype=float32)

In [7]:
## load an example DUMP file
mdaTraj = MDAnalysis.Universe('Model.cfg', format='lammpsdump') 
mdaTraj.atoms.bbox()

array([[-16.257025, -16.257025,   0.      ],
       [  8.12851 ,  -8.128512, 113.799164]], dtype=float32)

In [9]:
dir(mdaTraj.atoms)

['_SETATTR_WHITELIST',
 '__add__',
 '__and__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__or__',
 '__radd__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__weakref__',
 '__xor__',
 '_add_prop',
 '_cache',
 '_derived_class',
 '_is_group',
 '_ix',
 '_mix',
 '_subclass',
 '_u',
 '_unique_restore_mask',
 'accumulate',
 'align_principal_axis',
 'angle',
 'asphericity',
 'atoms',
 'bbox',
 'bond',
 'bsphere',
 'center',
 'center_of_geometry',
 'center_of_mass',
 'centroid',
 'cmap',
 'concatenate',
 'convert_to',
 'copy',
 'difference',
 'dihedral',
 'dimensions',
 'forces',
 'groupby',
 'guess_bonds',
 'ids',
 'improper',
 'indices',
 'intersection',


## 4. TRAVIS
https://aip.scitation.org/doi/10.1063/5.0005078

## 5. pytim
https://aip.scitation.org/doi/10.1063/5.0005078

## 6. pytraj
https://amber-md.github.io/pytraj/latest/tutorials/index.html

## 7. RDkit
https://www.rdkit.org/docs/index.html

# II. More tools
1. Voronoi: tess  
2. Shapely



# III.Compute SASA
## 1. Pytim
## 2. MDtraj
## 3. RDkit


In [61]:
# array of arrays of the same sizes
a = np.array([np.array([1,2]), np.array([3,4]), np.array([5, 6])])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [67]:
b = []
a = [1,2]
c = np.array([3,4])
b.append(a)
b.append(c)
print(b)

[[1, 2], array([3, 4])]


# IV. Visualization Tools
## 1. Ovito
## 2. NGLView
https://ambermd.org/tutorials/analysis/tutorial_notebooks/nglview_movie/index.html

In [1]:
import nglview
view = nglview.show_pdbid("3pqr")  # load "3pqr" from RCSB PDB and display viewer widget
view

NGLWidget()